const searchBarTypes = {
    SEARCH_PRODUCTS_REQUEST: "SEARCH_PRODUCTS_REQUEST",
    SEARCH_PRODUCTS_SUCCESS: "SEARCH_PRODUCTS_SUCCESS",
    SEARCH_PRODUCTS_FAILURE: "SEARCH_PRODUCTS_FAILURE",
};

export default searchBarTypes;